### ISSUE TITLE
Error with API non syntax

### ISSUE THREAD

**Issue by Fitsbit** [DrewStewart7/ShortFormGenerator#1]
Hey man, liked the idea and wanted to try it out but got this error: any idea why and can you help me with it?

2024-02-17 18:29:58,814 - TikTokApi.tiktok - ERROR - Got an unexpected status code: {'log_pb': {'impr_id': '20240218022959A4C5CEC0BD98BF640B62'}, 'statusCode': 10201, 'statusMsg': '', 'status_code': 10201, 'status_msg': ''}

![image](https://github.com/DrewStewart7/ShortFormGenerator/assets/107160828/576f72e7-7dab-47fc-93bb-44fcd186b187)

**Comment by DrewStewart7** [comment]
Hi. Thank you for being interested in the project! I'm sorry you're having an issue with it. This seems to be an issue with the TikTokApi. A quick google search doesn't shed much light on a possible solution. Just to check, did you modify the code at all to make the browser headless? If so, I did find an example of someone else having the same issue and making it headless = False fixed it for them. If you didn't modify the code, what is your operating system and are you able to access TikTok on your machine? Also, does a browser open when you run the program?
