### ISSUE TITLE
Stuck On Downloading Video

### ISSUE THREAD

**Issue by JustAiden9** [DrewStewart7/ShortFormGenerator#2]
Just as the title says, I try to run it and it all works great! Then when it hits the downloading video it gets stuck and just stops and never finishes.

**Comment by DrewStewart7** [comment]
Hi, thank you for bringing this issue to my attention! It appears that the 3rd party API I was using to download the videos has enabled cloudflare on their site. I will attempt to find a solution and will let you know/update the repo when I find one.

**Comment by DrewStewart7** [comment]
> Just as the title says, I try to run it and it all works great! Then when it hits the downloading video it gets stuck and just stops and never finishes.

Hi again. The repo has been updated! Please give it a try and respond here with the result. Thank you again!

**Comment by JustAiden9** [comment]
It works now!
